# -*- coding: utf-8 -*-
"""image_gen.ipynb

Automatically generated by Colaboratory.

Original file is located at
https://colab.research.google.com/drive/1Dm_petoADmR18PrpLU8Ywr3_sqTH-JZ9

#Image Generator from Pre-Trained Model
"""


# Imports
import streamlit as st
from tensorflow import keras
import matplotlib.pyplot as plt
import numpy as np
from PIL import Image 


st.title("Cat Image Generator")

generator = keras.models.load_model('generator_64_64_z64_final_epoch.h5')

# Create a random noise and generate a sample
batch_size = 64
z_dimension = 64
noise = np.random.normal(0, 1, (batch_size, z_dimension))
gen_imgs = generator.predict(noise)

# Visualize the generated sample
# plt.imshow(gen_imgs[0, :, :, 0], cmap='gray')
#st.pyplot(gen_imgs[0, :, :, 0], cmap='gray') 
img = Image.fromarray(gen_imgs[0, :, :, 0], 'L')
big_img = img.resize((500,500))
st.image(big_img)








